import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    play: 'Play', puzzles: 'Puzzles', learn: 'Learn', profile: 'Profile',
    practice: 'Practice', login: 'Login', signup: 'Sign Up', logout: 'Logout',
    welcome: 'Welcome back', guest: 'Play as Guest',
    dashboard_title: 'Master the Board',
    dashboard_subtitle: 'Play, learn, and conquer — your ultimate chess experience.',
    settings: 'Settings', board_theme: 'Board Theme', language: 'Language',
    piece_cursor: 'Piece Cursor', difficulty: 'Difficulty',
    beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced',
    your_turn: 'Your turn', thinking: 'Stockfish is thinking...',
    checkmate: 'Checkmate', draw: 'Draw', check: 'Check',
    new_game: 'New Game', undo: 'Undo', resign: 'Resign',
    move_history: 'Move History', recent_matches: 'Recent Matches',
    match_history: 'Match History', no_matches: 'No matches yet. Play your first game!',
    played: 'Played', wins: 'Wins', losses: 'Losses', win_rate: 'Win Rate',
    show_hint: 'Show Hint', hide_hint: 'Hide Hint', restart: 'Restart',
    correct: 'Correct! Well done!', incorrect: 'Incorrect. Try again!',
    all_solved: 'You solved all puzzles! Amazing!',
    learn_title: 'Learn to Play Chess',
    learn_subtitle: 'Understand every piece and master the special moves.',
    special_rules: 'Special Rules', tip: 'Tip',
    practice_title: 'Practice Arena',
    practice_subtitle: 'Sharpen your skills with focused training.',
    openings: 'Openings', endgames: 'Endgames', tactics: 'Tactics',
    guest_profile: 'Guest Profile',
    guest_profile_msg: "You're playing as a guest. Create an account to track your ELO rating and match history!",
    date: 'Date', opponent: 'Opponent', result: 'Result', accuracy: 'Accuracy',
    quick_play: 'Quick Play', start_playing: 'Start Playing',
    vs_stockfish: 'Play vs Stockfish',
    choose_challenge: 'Choose your challenge level.',
    drag_or_click: 'Drag or click a piece to start.',
    play_desc: 'Challenge the Stockfish engine at beginner, intermediate, or advanced level.',
    puzzles_desc: 'Sharpen your tactics by solving hand-crafted chess puzzles.',
    learn_desc: 'Master the rules: piece movements, special moves, and strategy.',
    profile_desc: 'Track your ELO rating, win/loss record, and full match history.',
    practice_desc: 'Train with focused opening, endgame, and tactical drills.',
  },
  es: {
    play: 'Jugar', puzzles: 'Puzzles', learn: 'Aprender', profile: 'Perfil',
    practice: 'Práctica', login: 'Iniciar Sesión', signup: 'Registrarse', logout: 'Salir',
    welcome: 'Bienvenido', guest: 'Jugar como Invitado',
    dashboard_title: 'Domina el Tablero',
    dashboard_subtitle: 'Juega, aprende y conquista — tu experiencia de ajedrez definitiva.',
    settings: 'Ajustes', board_theme: 'Tema del Tablero', language: 'Idioma',
    piece_cursor: 'Cursor de Pieza', difficulty: 'Dificultad',
    beginner: 'Principiante', intermediate: 'Intermedio', advanced: 'Avanzado',
    your_turn: 'Tu turno', thinking: 'Stockfish está pensando...',
    checkmate: 'Jaque Mate', draw: 'Tablas', check: 'Jaque',
    new_game: 'Nueva Partida', undo: 'Deshacer', resign: 'Rendirse',
    move_history: 'Historial de Movimientos', recent_matches: 'Partidas Recientes',
    match_history: 'Historial de Partidas', no_matches: '¡Sin partidas aún. Juega tu primera!',
    played: 'Jugadas', wins: 'Victorias', losses: 'Derrotas', win_rate: 'Tasa de Victoria',
    show_hint: 'Pista', hide_hint: 'Ocultar Pista', restart: 'Reiniciar',
    correct: '¡Correcto! ¡Bien hecho!', incorrect: 'Incorrecto. ¡Intenta de nuevo!',
    all_solved: '¡Resolviste todos los puzzles! ¡Increíble!',
    learn_title: 'Aprende a Jugar Ajedrez',
    learn_subtitle: 'Comprende cada pieza y domina los movimientos especiales.',
    special_rules: 'Reglas Especiales', tip: 'Consejo',
    practice_title: 'Arena de Práctica',
    practice_subtitle: 'Mejora tus habilidades con entrenamiento enfocado.',
    openings: 'Aperturas', endgames: 'Finales', tactics: 'Tácticas',
    guest_profile: 'Perfil de Invitado',
    guest_profile_msg: 'Estás jugando como invitado. ¡Crea una cuenta para seguir tu rating!',
    date: 'Fecha', opponent: 'Oponente', result: 'Resultado', accuracy: 'Precisión',
    quick_play: 'Juego Rápido', start_playing: 'Comenzar a Jugar',
    vs_stockfish: 'Jugar vs Stockfish',
    choose_challenge: 'Elige tu nivel de desafío.',
    drag_or_click: 'Arrastra o haz clic en una pieza para comenzar.',
    play_desc: 'Desafía al motor Stockfish en nivel principiante, intermedio o avanzado.',
    puzzles_desc: 'Agudiza tu táctica resolviendo puzzles de ajedrez.',
    learn_desc: 'Domina las reglas: movimientos de piezas, movimientos especiales y estrategia.',
    profile_desc: 'Sigue tu ELO, registro de victorias/derrotas e historial completo.',
    practice_desc: 'Entrena con ejercicios enfocados de apertura, final y táctica.',
  },
  hi: {
    play: 'खेलें', puzzles: 'पहेलियाँ', learn: 'सीखें', profile: 'प्रोफ़ाइल',
    practice: 'अभ्यास', login: 'लॉगिन', signup: 'साइन अप', logout: 'लॉगआउट',
    welcome: 'वापस स्वागत है', guest: 'अतिथि के रूप में खेलें',
    dashboard_title: 'बोर्ड पर राज करें',
    dashboard_subtitle: 'खेलें, सीखें और जीतें — आपका परम शतरंज अनुभव।',
    settings: 'सेटिंग्स', board_theme: 'बोर्ड थीम', language: 'भाषा',
    piece_cursor: 'पीस कर्सर', difficulty: 'कठिनाई',
    beginner: 'शुरुआती', intermediate: 'मध्यवर्ती', advanced: 'उन्नत',
    your_turn: 'आपकी बारी', thinking: 'स्टॉकफिश सोच रहा है...',
    checkmate: 'शह और मात', draw: 'ड्रॉ', check: 'शह',
    new_game: 'नया खेल', undo: 'पूर्ववत', resign: 'हार मानें',
    move_history: 'चाल इतिहास', recent_matches: 'हालिया मैच',
    match_history: 'मैच इतिहास', no_matches: 'कोई मैच नहीं। अपना पहला खेल खेलें!',
    played: 'खेले', wins: 'जीत', losses: 'हार', win_rate: 'जीत दर',
    show_hint: 'संकेत दिखाएं', hide_hint: 'संकेत छुपाएं', restart: 'पुनरारंभ',
    correct: 'सही! शाबाश!', incorrect: 'गलत। फिर से कोशिश करें!',
    all_solved: 'आपने सभी पहेलियाँ हल कर लीं! शानदार!',
    learn_title: 'शतरंज खेलना सीखें',
    learn_subtitle: 'हर मोहरे को समझें और विशेष चालें सीखें।',
    special_rules: 'विशेष नियम', tip: 'सुझाव',
    practice_title: 'अभ्यास अखाड़ा',
    practice_subtitle: 'केंद्रित प्रशिक्षण से अपने कौशल को निखारें।',
    openings: 'शुरुआत', endgames: 'अंतिम खेल', tactics: 'रणनीति',
    guest_profile: 'अतिथि प्रोफ़ाइल',
    guest_profile_msg: 'आप अतिथि के रूप में खेल रहे हैं। रेटिंग ट्रैक करने के लिए खाता बनाएं!',
    date: 'तारीख', opponent: 'प्रतिद्वंद्वी', result: 'परिणाम', accuracy: 'सटीकता',
    quick_play: 'त्वरित खेल', start_playing: 'खेलना शुरू करें',
    vs_stockfish: 'स्टॉकफिश के विरुद्ध खेलें',
    choose_challenge: 'अपना चुनौती स्तर चुनें।',
    drag_or_click: 'शुरू करने के लिए एक मोहरे को खींचें या क्लिक करें।',
    play_desc: 'शुरुआती, मध्यवर्ती या उन्नत स्तर पर स्टॉकफिश इंजन को चुनौती दें।',
    puzzles_desc: 'शतरंज पहेलियाँ हल करके अपनी रणनीति तेज करें।',
    learn_desc: 'नियम सीखें: मोहरों की चाल, विशेष चालें और रणनीति।',
    profile_desc: 'अपनी ELO रेटिंग, जीत/हार रिकॉर्ड और पूरा मैच इतिहास ट्रैक करें।',
    practice_desc: 'शुरुआत, अंतिम खेल और सामरिक अभ्यासों के साथ प्रशिक्षण।',
  },
  fr: {
    play: 'Jouer', puzzles: 'Puzzles', learn: 'Apprendre', profile: 'Profil',
    practice: 'Entraînement', login: 'Connexion', signup: "S'inscrire", logout: 'Déconnexion',
    welcome: 'Bienvenue', guest: 'Jouer en invité',
    dashboard_title: 'Maîtrisez l\'Échiquier',
    dashboard_subtitle: 'Jouez, apprenez et conquérez — votre expérience d\'échecs ultime.',
    settings: 'Paramètres', board_theme: 'Thème du plateau', language: 'Langue',
    piece_cursor: 'Curseur pièce', difficulty: 'Difficulté',
    beginner: 'Débutant', intermediate: 'Intermédiaire', advanced: 'Avancé',
    your_turn: 'Votre tour', thinking: 'Stockfish réfléchit...',
    checkmate: 'Échec et mat', draw: 'Nulle', check: 'Échec',
    new_game: 'Nouvelle partie', undo: 'Annuler', resign: 'Abandonner',
    move_history: 'Historique des coups', recent_matches: 'Parties récentes',
    match_history: 'Historique des parties', no_matches: 'Pas encore de parties. Jouez votre première !',
    played: 'Jouées', wins: 'Victoires', losses: 'Défaites', win_rate: 'Taux de victoire',
    show_hint: 'Indice', hide_hint: 'Masquer l\'indice', restart: 'Recommencer',
    correct: 'Correct ! Bien joué !', incorrect: 'Incorrect. Réessayez !',
    all_solved: 'Vous avez résolu tous les puzzles ! Incroyable !',
    learn_title: 'Apprendre les Échecs',
    learn_subtitle: 'Comprenez chaque pièce et maîtrisez les coups spéciaux.',
    special_rules: 'Règles spéciales', tip: 'Conseil',
    practice_title: 'Arène d\'entraînement',
    practice_subtitle: 'Affûtez vos compétences avec un entraînement ciblé.',
    openings: 'Ouvertures', endgames: 'Finales', tactics: 'Tactiques',
    guest_profile: 'Profil invité',
    guest_profile_msg: 'Vous jouez en tant qu\'invité. Créez un compte pour suivre votre classement !',
    date: 'Date', opponent: 'Adversaire', result: 'Résultat', accuracy: 'Précision',
    quick_play: 'Partie rapide', start_playing: 'Commencer à jouer',
    vs_stockfish: 'Jouer contre Stockfish',
    choose_challenge: 'Choisissez votre niveau de défi.',
    drag_or_click: 'Glissez ou cliquez sur une pièce pour commencer.',
    play_desc: 'Défiez le moteur Stockfish au niveau débutant, intermédiaire ou avancé.',
    puzzles_desc: 'Affûtez votre tactique en résolvant des puzzles d\'échecs.',
    learn_desc: 'Maîtrisez les règles : mouvements des pièces, coups spéciaux et stratégie.',
    profile_desc: 'Suivez votre ELO, votre bilan victoires/défaites et votre historique.',
    practice_desc: 'Entraînez-vous avec des exercices d\'ouverture, de finale et de tactique.',
  },
  de: {
    play: 'Spielen', puzzles: 'Rätsel', learn: 'Lernen', profile: 'Profil',
    practice: 'Training', login: 'Anmelden', signup: 'Registrieren', logout: 'Abmelden',
    welcome: 'Willkommen zurück', guest: 'Als Gast spielen',
    dashboard_title: 'Beherrsche das Brett',
    dashboard_subtitle: 'Spiele, lerne und erobere — dein ultimatives Schacherlebnis.',
    settings: 'Einstellungen', board_theme: 'Brett-Thema', language: 'Sprache',
    piece_cursor: 'Figur-Cursor', difficulty: 'Schwierigkeit',
    beginner: 'Anfänger', intermediate: 'Fortgeschritten', advanced: 'Experte',
    your_turn: 'Dein Zug', thinking: 'Stockfish denkt nach...',
    checkmate: 'Schachmatt', draw: 'Remis', check: 'Schach',
    new_game: 'Neues Spiel', undo: 'Rückgängig', resign: 'Aufgeben',
    move_history: 'Zughistorie', recent_matches: 'Letzte Partien',
    match_history: 'Partiehistorie', no_matches: 'Noch keine Partien. Spiele deine erste!',
    played: 'Gespielt', wins: 'Siege', losses: 'Niederlagen', win_rate: 'Siegrate',
    show_hint: 'Hinweis', hide_hint: 'Hinweis verbergen', restart: 'Neustart',
    correct: 'Richtig! Gut gemacht!', incorrect: 'Falsch. Versuche es erneut!',
    all_solved: 'Du hast alle Rätsel gelöst! Erstaunlich!',
    learn_title: 'Schach lernen',
    learn_subtitle: 'Verstehe jede Figur und meistere die Sonderzüge.',
    special_rules: 'Sonderregeln', tip: 'Tipp',
    practice_title: 'Trainingsarena',
    practice_subtitle: 'Schärfe deine Fähigkeiten mit gezieltem Training.',
    openings: 'Eröffnungen', endgames: 'Endspiele', tactics: 'Taktiken',
    guest_profile: 'Gastprofil',
    guest_profile_msg: 'Du spielst als Gast. Erstelle ein Konto, um deine Wertung zu verfolgen!',
    date: 'Datum', opponent: 'Gegner', result: 'Ergebnis', accuracy: 'Genauigkeit',
    quick_play: 'Schnellspiel', start_playing: 'Jetzt spielen',
    vs_stockfish: 'Gegen Stockfish spielen',
    choose_challenge: 'Wähle deine Herausforderungsstufe.',
    drag_or_click: 'Ziehe oder klicke eine Figur, um zu beginnen.',
    play_desc: 'Fordere die Stockfish-Engine auf Anfänger-, Fortgeschrittenen- oder Expertenniveau.',
    puzzles_desc: 'Schärfe deine Taktik durch das Lösen von Schachrätseln.',
    learn_desc: 'Meistere die Regeln: Figurenbewegungen, Sonderzüge und Strategie.',
    profile_desc: 'Verfolge deine ELO-Wertung, Gewinn-/Verlustbilanz und Partiehistorie.',
    practice_desc: 'Trainiere mit gezielten Eröffnungs-, Endspiel- und Taktikübungen.',
  }
};

const LANG_LABELS = {
  en: '🇬🇧 English',
  es: '🇪🇸 Español',
  hi: '🇮🇳 हिन्दी',
  fr: '🇫🇷 Français',
  de: '🇩🇪 Deutsch',
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('chess7k_lang') || 'en');

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('chess7k_lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t, LANG_LABELS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
